In [1]:
import csv
import numpy
reader = csv.reader(open("Jan_Breaks.csv", "r"), delimiter=",")
x = list(reader)

result = numpy.array(x[1:][:]).astype("float")

In [22]:
X=result[:,1:7]
y=result[:,7]
print(y.shape)
y=y.reshape(357,1)
print(X,y)

(357,)
[[3.600e+01 6.000e+00 5.625e-01 7.500e-01 1.000e+00 2.015e+03]
 [3.600e+01 6.000e+00 5.625e-01 7.500e-01 1.000e+00 2.017e+03]
 [1.600e+01 4.000e+00 1.000e+00 1.000e+00 1.000e+00 2.011e+03]
 ...
 [1.210e+02 1.100e+01 1.440e+02 1.200e+01 1.000e+00 2.015e+03]
 [3.600e+01 6.000e+00 4.000e+02 2.000e+01 1.000e+00 2.006e+03]
 [3.600e+01 6.000e+00 4.000e+02 2.000e+01 1.000e+00 2.011e+03]] [[ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 2.]
 [ 3.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 2.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 4.]
 [ 1.]
 [ 2.]
 [ 2.]
 [ 4.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 3.]
 [ 2.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 2.]
 [ 1.]
 [ 3.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 2.]
 [ 1.]
 [ 1.]
 [ 6.]
 [ 3.]
 [ 7.]
 [ 3.]
 [ 4.]
 [ 4.]
 [ 7.]
 [10.]
 [ 7.]
 [ 2.]
 [ 4.]
 [10.]
 [ 1.]
 [ 1.]


In [23]:
w=numpy.linalg.inv(X.transpose()@X)@X.transpose()@y
w

array([[-1.15886847e-01],
       [ 1.30518476e+00],
       [-2.09420679e-02],
       [ 2.23325946e-01],
       [-7.71064961e+01],
       [ 3.74741856e-02]])

In [24]:
import csv
import numpy
reader = csv.reader(open("test.csv", "r"), delimiter=",")
x = list(reader)

test = numpy.array(x[1:][:]).astype("float")
test=test[:,1:]
print(test)

[[1.225e+01 3.500e+00 6.400e+01 8.000e+00 1.000e+00 2.020e+03]
 [1.600e+01 4.000e+00 3.600e+01 6.000e+00 1.000e+00 2.020e+03]
 [2.025e+01 4.500e+00 3.600e+01 6.000e+00 1.000e+00 2.020e+03]
 [2.500e+01 5.000e+00 3.600e+01 6.000e+00 1.000e+00 2.020e+03]
 [2.500e+01 5.000e+00 1.000e+02 1.000e+01 1.000e+00 2.020e+03]
 [2.500e+01 5.000e+00 1.440e+02 1.200e+01 1.000e+00 2.020e+03]
 [3.025e+01 5.500e+00 3.600e+01 6.000e+00 1.000e+00 2.020e+03]
 [3.025e+01 5.500e+00 6.400e+01 8.000e+00 1.000e+00 2.020e+03]
 [3.025e+01 5.500e+00 1.000e+02 1.000e+01 1.000e+00 2.020e+03]
 [3.600e+01 6.000e+00 1.000e+00 1.000e+00 1.000e+00 2.020e+03]
 [3.600e+01 6.000e+00 1.600e+01 4.000e+00 1.000e+00 2.020e+03]
 [3.600e+01 6.000e+00 3.600e+01 6.000e+00 1.000e+00 2.020e+03]
 [3.600e+01 6.000e+00 6.400e+01 8.000e+00 1.000e+00 2.020e+03]
 [3.600e+01 6.000e+00 1.000e+02 1.000e+01 1.000e+00 2.020e+03]
 [3.600e+01 6.000e+00 1.440e+02 1.200e+01 1.000e+00 2.020e+03]
 [4.225e+01 6.500e+00 3.600e+01 6.000e+00 1.000e+00 2.0

In [25]:
y_result=test@w
y_result

array([[2.1862068 ],
       [2.54394952],
       [2.7040228 ],
       [2.80615266],
       [2.3591641 ],
       [1.884365  ],
       [2.85033909],
       [2.71061308],
       [2.40335053],
       [2.45292474],
       [2.80877157],
       [2.8365821 ],
       [2.69685609],
       [2.38959354],
       [1.91479445],
       [2.76488169],
       [2.62515568],
       [2.31789313],
       [2.25158049],
       [2.41208024],
       [2.53069584],
       [2.60742732],
       [2.63523785],
       [2.49551184],
       [2.18824929],
       [1.7134502 ],
       [2.00066203],
       [1.75513135],
       [1.53722827],
       [0.64056294]])

In [26]:
info=test[:,(1,3)]
info=numpy.hstack((info,y_result))

In [27]:
info

array([[ 3.5       ,  8.        ,  2.1862068 ],
       [ 4.        ,  6.        ,  2.54394952],
       [ 4.5       ,  6.        ,  2.7040228 ],
       [ 5.        ,  6.        ,  2.80615266],
       [ 5.        , 10.        ,  2.3591641 ],
       [ 5.        , 12.        ,  1.884365  ],
       [ 5.5       ,  6.        ,  2.85033909],
       [ 5.5       ,  8.        ,  2.71061308],
       [ 5.5       , 10.        ,  2.40335053],
       [ 6.        ,  1.        ,  2.45292474],
       [ 6.        ,  4.        ,  2.80877157],
       [ 6.        ,  6.        ,  2.8365821 ],
       [ 6.        ,  8.        ,  2.69685609],
       [ 6.        , 10.        ,  2.38959354],
       [ 6.        , 12.        ,  1.91479445],
       [ 6.5       ,  6.        ,  2.76488169],
       [ 6.5       ,  8.        ,  2.62515568],
       [ 6.5       , 10.        ,  2.31789313],
       [ 7.        ,  1.        ,  2.25158049],
       [ 7.        ,  2.        ,  2.41208024],
       [ 7.        ,  3.        ,  2.530

In [29]:
import pandas as pd
column_values=["pipe_depth","pipe_size","Number"]
df = pd.DataFrame(data = info,    
                  columns = column_values)


In [30]:
df

pipe_depth  pipe_size    Number
0          3.5        8.0  2.186207
1          4.0        6.0  2.543950
2          4.5        6.0  2.704023
3          5.0        6.0  2.806153
4          5.0       10.0  2.359164
5          5.0       12.0  1.884365
6          5.5        6.0  2.850339
7          5.5        8.0  2.710613
8          5.5       10.0  2.403351
9          6.0        1.0  2.452925
10         6.0        4.0  2.808772
11         6.0        6.0  2.836582
12         6.0        8.0  2.696856
13         6.0       10.0  2.389594
14         6.0       12.0  1.914794
15         6.5        6.0  2.764882
16         6.5        8.0  2.625156
17         6.5       10.0  2.317893
18         7.0        1.0  2.251580
19         7.0        2.0  2.412080
20         7.0        3.0  2.530696
21         7.0        4.0  2.607427
22         7.0        6.0  2.635238
23         7.0        8.0  2.495512
24         7.0       10.0  2.188249
25         7.0       12.0  1.713450
26         7.5       10.0  2.000662
27         8.0       10.0  1.755131
28         9.0        6.0  1.537228
29        10.0        6.0  0.640563

In [31]:
df.to_csv('manupilation.csv')