In [1]:
import csv
import numpy
from numpy import genfromtxt
my_data = genfromtxt('dataset/training_matrixv2.csv', delimiter=',')
train = my_data[1:,1:]

In [2]:
training_x=[]
training_y=[]
for i in range(1,13):
    mat=train.copy()
    mat=mat[mat[:,10] == i]
    mat=mat[:,:10]
    training_x.append(mat[:,:9])
    training_y.append(mat[:,9])

training_x[0][0]

array([2.160000e+02, 3.600000e+01, 6.000000e+00, 5.120000e+02,
       6.400000e+01, 8.000000e+00, 3.996001e+06, 1.999000e+03,
       1.000000e+00])

In [3]:
w=[]
for i in range(12):
    X=training_x[i]
    y=training_y[i]
    w.append(numpy.linalg.inv(X.transpose()@X)@X.transpose()@y)
w

[array([ 1.19217439e-01, -2.76797829e+00,  1.98798493e+01,  1.24870617e-02,
        -4.05499745e-01,  3.32229224e+00,  6.32282734e-03, -2.54819500e+01,
         2.56258600e+04]),
 array([ 9.06948857e-02, -2.24413574e+00,  1.68665901e+01,  1.75566181e-02,
        -4.58566180e-01,  3.25043683e+00, -1.66356925e-02,  6.70035801e+01,
        -6.75097583e+04]),
 array([ 1.98884009e-02, -5.82235733e-01,  4.83943845e+00,  8.54856891e-03,
        -2.19293720e-01,  1.59039705e+00, -1.08954211e-02,  4.39397246e+01,
        -4.43136563e+04]),
 array([-5.31408670e-03,  3.09696303e-02,  8.76206516e-02,  4.17567238e-03,
        -9.63827701e-02,  5.68105466e-01,  1.42598285e-03, -5.69743721e+00,
         5.69081926e+03]),
 array([-4.01470356e-04, -6.48533014e-03,  1.40988194e-01,  3.18186276e-04,
        -1.42029344e-02,  1.80445920e-01, -1.24750874e-03,  5.07123449e+00,
        -5.15317704e+03]),
 array([ 1.03981498e-02, -2.40040447e-01,  1.72902432e+00,  1.30061538e-03,
        -3.51797880e-02,  2.3

In [4]:
test_data = genfromtxt('dataset/test.csv', delimiter=',')
test = test_data[1:,1:]

In [5]:
test_x=[]
for i in range(1,13):
    mat=test.copy()
    mat=mat[mat[:,9] == i]
    mat=mat[:,:9]
    test_x.append(mat)

test_x[0][0]

array([2.160000e+02, 3.600000e+01, 6.000000e+00, 1.000000e+00,
       1.000000e+00, 1.000000e+00, 4.084441e+06, 2.021000e+03,
       1.000000e+00])

In [6]:
result=[]
prediction=[]
for i in range(0,12):
    X=test_x[i]
    weight=w[i]
    y=X@weight
    y = numpy.reshape(y,(y.size,1))
    X=numpy.hstack((X,y))
    m,n=X.shape
    imatrix=numpy.full((m,1),i+1,dtype=int)
    prediction.append(numpy.hstack((X,imatrix)))
prediction[0]
   

array([[ 2.16000000e+02,  3.60000000e+01,  6.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         4.08444100e+06,  2.02100000e+03,  1.00000000e+00,
         3.66427234e-01,  1.00000000e+00],
       [ 3.43000000e+02,  4.90000000e+01,  7.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         4.08444100e+06,  2.02100000e+03,  1.00000000e+00,
        -5.96826446e-01,  1.00000000e+00],
       [ 3.43000000e+02,  4.90000000e+01,  7.00000000e+00,
         8.00000000e+00,  4.00000000e+00,  2.00000000e+00,
         4.08444100e+06,  2.02100000e+03,  1.00000000e+00,
         1.59637599e+00,  1.00000000e+00],
       [ 3.43000000e+02,  4.90000000e+01,  7.00000000e+00,
         2.70000000e+01,  9.00000000e+00,  3.00000000e+00,
         4.08444100e+06,  2.02100000e+03,  1.00000000e+00,
         3.12842367e+00,  1.00000000e+00],
       [ 2.16000000e+02,  3.60000000e+01,  6.00000000e+00,
         6.40000000e+01,  1.60000000e+01,  4.00000000e+00,
  

In [7]:
plotmatrix=prediction[0]
for i in range(1,12):
    #plotmatrix=plotmatrix.append(plotmatrix,prediction[1])
    plotmatrix=numpy.vstack((plotmatrix,prediction[i]))

plotmatrix=plotmatrix[:,(2,5,9,10)]
plotmatrix

array([[ 6.        ,  1.        ,  0.36642723,  1.        ],
       [ 7.        ,  1.        , -0.59682645,  1.        ],
       [ 7.        ,  2.        ,  1.59637599,  1.        ],
       [ 7.        ,  3.        ,  3.12842367,  1.        ],
       [ 6.        ,  4.        ,  5.03749265,  1.        ],
       [ 6.        ,  4.        ,  5.03749265,  1.        ],
       [ 7.        ,  4.        ,  4.07423897,  1.        ],
       [ 4.        ,  6.        ,  2.94893199,  1.        ],
       [ 4.        ,  6.        ,  2.94893199,  1.        ],
       [ 4.5       ,  6.        ,  4.35872196,  1.        ],
       [ 4.5       ,  6.        ,  4.35872196,  1.        ],
       [ 5.        ,  6.        ,  5.1892405 ,  1.        ],
       [ 5.        ,  6.        ,  5.1892405 ,  1.        ],
       [ 5.5       ,  6.        ,  5.52990069,  1.        ],
       [ 6.        ,  6.        ,  5.4701156 ,  1.        ],
       [ 6.        ,  6.        ,  5.4701156 ,  1.        ],
       [ 6.5       ,  6.

In [8]:
import pandas as pd
column_values=["pipe_depth","pipe_size","Number","Month"]
df = pd.DataFrame(data = plotmatrix,    
                  columns = column_values)
df.to_csv('manupilationv2.csv')

In [9]:
reader = csv.reader(open("dataset/test.csv", "r"), delimiter=",")
x = list(reader)

test = numpy.array(x[1:][:]).astype("float")
test=test[:,1:]
print(test)

[[2.160e+02 3.600e+01 6.000e+00 ... 2.021e+03 1.000e+00 1.000e+00]
 [3.430e+02 4.900e+01 7.000e+00 ... 2.021e+03 1.000e+00 1.000e+00]
 [3.430e+02 4.900e+01 7.000e+00 ... 2.021e+03 1.000e+00 1.000e+00]
 ...
 [2.160e+02 3.600e+01 6.000e+00 ... 2.021e+03 1.000e+00 1.200e+01]
 [3.430e+02 4.900e+01 7.000e+00 ... 2.021e+03 1.000e+00 1.200e+01]
 [2.160e+02 3.600e+01 6.000e+00 ... 2.021e+03 1.000e+00 1.200e+01]]


In [10]:
y_result=test@w
y_result

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 12 is different from 10)

In [ ]:
info=test[:,(1,3)]
info=numpy.hstack((info,y_result))

In [ ]:
info

In [ ]:
import pandas as pd
column_values=["pipe_depth","pipe_size","Number"]
df = pd.DataFrame(data = info,    
                  columns = column_values)


In [ ]:
df

In [ ]:
df.to_csv('manupilation.csv')